version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  func:
    image: func-test:dev
    build:
      context: ../../repos/Functions
      dockerfile: Dockerfile
    init: true
