version: '3.4'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: DDD_DB
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=12345678_qaz

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  func:
    image: func-test:dev
    build:
      context: .
      dockerfile: Functions/Dockerfile
    init: true

  message-broker:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: message-broker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  email-sender:
    image: ${DOCKER_REGISTRY-}consoleapp
    restart: on-failure
    build:
      context: .
      dockerfile: EmailsSender/Dockerfile  